### ISSUE TITLE
Build Error From eso-pic.sty

### ISSUE THREAD

**Issue by DubPFrye** [rolfn/eso-pic#2]
Hello, Just wanted to let you know that I recently reinstalled MiKTeX and all of the packages, and recompiled a known-good LaTeX document. I got an error in eso-pic.sty, line 188, "undefined control sequence. There was also an error for "Missing \begin{document}. 

I  replaced eso-pic.sty with the one from my old PC, was dated 1999/12/01. The errors went away and I was able to build successfully.

Thanks,
Patrick Frye

**Comment by rolfn** [comment]
I can't do anything with such an inadequate error statement! Show me with a minimal (!) Document that an error occurs and which one it is. Add 
```
\listfiles
```
 as the first line in the document and show me the list of the packages used (log file).

**Comment by DubPFrye** [comment]
Hello, My apologies, I am only a user and not familiar with the error statement requirements. I was able to isolate the issue to attached tex file.

Thanks,
Frye
[eso-pic_test.tex.txt](https://github.com/rolfn/eso-pic/files/5973347/eso-pic_test.tex.txt)
[eso-pic_test.log.txt](https://github.com/rolfn/eso-pic/files/5973348/eso-pic_test.log.txt)

**Comment by rolfn** [comment]
OK, I can see. You are using the new version of eso-pic with a completely outdated LaTeX format. See the warning in .log:
```
LaTeX Warning: You have requested release `2020-10-01' of LaTeX,
               but only release `2017-04-15' is available.
```
My mistake: I only write a warning, but it would be better to cancel the LaTeX run with an error notice.

Conclusion: Renew your TeX installation so that you have at least the LaTeX version `2020-10-01`.
