### ISSUE TITLE
Bug in the horizontal lines of the grid displayed by eso-pic

### ISSUE THREAD

**Issue by quark67** [rolfn/eso-pic#4]
Here is a code:

```latex
\documentclass[12pt,a4paper]{article}

\usepackage{xcolor}
\usepackage[grid, gridunit=mm, gridcolor=orange, subgridcolor=blue!20,gridBG]{eso-pic}
\gridSetup{1mm}{1}{1}{10}{1}

\begin{document}

test 

\end{document}
```

Whatever I put in `\gridSetup`, the horizontal lines are always separated by 2 cm, and don't have sub-lines.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/9338576/223505551-39dcb9cd-ba3d-47a1-aa20-adaba6fcb188.png">

In vertical, instead of 10, 20, 30, we must read 20, 40, 60. And several horizontal lines are missing:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/9338576/223508501-3647fb1c-341f-4e0f-8d62-d1623fb1c1d0.png">

**Comment by quark67** [comment]
See here a workaround: https://tex.stackexchange.com/a/443234/132405

**Comment by rolfn** [comment]
Thank you for the bug report. I added the correction (version 3.0b). In a few days this version will be on CTAN.
